- name: Ensure the {{ semaphore_compose_dir }} directory exists
  file:
    path: "{{ semaphore_compose_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Deploy compose file from template
  template:
    src: "{{ compose_template }}"
    dest: "{{ semaphore_compose_dir }}/docker-compose.yml"
  register: compose_deploy

- name: Check if SemaphoreUI container is running
  shell: docker ps -q -f name=semaphore
  register: semaphore_running
  changed_when: false

- name: Handle compose file changes (restart container)
  block:
    - name: Bring down SemaphoreUI container if running
      shell: docker compose down
      args:
        chdir: "{{ semaphore_compose_dir }}"
      when: semaphore_running.stdout != ""

    - name: Prune unused docker containers
      shell: docker container prune -f
      when: semaphore_running.stdout != ""
      
    - name: Start SemaphoreUI using docker CLI (after change)
      shell: docker compose up -d
      args:
        chdir: "{{ semaphore_compose_dir }}"
  when: compose_deploy.changed

- name: Start SemaphoreUI using docker CLI if no changes detected
  shell: docker compose up -d
  args:
    chdir: "{{ semaphore_compose_dir }}"
  when: not compose_deploy.changed

- name: Wait for SemaphoreUI container to be running
  shell: docker inspect --format '{{ "{{" }}.State.Running{{ "}}" }}' semaphore
  register: container_status_final
  retries: 10
  delay: 10
  until: container_status_final.stdout | trim == "true"